# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return quasardb API build information.
#' 
#' Return build information of the underlying quasardb C API.
#' 
#' @return API build information
#' @export
#' @examples
#' qdb_build()
qdb_build <- function() {
    .Call('_quasardb__qdb_build', PACKAGE = 'quasardb')
}

#' Connect to a quasardb cluster.
#' 
#' Connect to a quasardb cluster described with the given URI and returns a handle to it.
#' The URI must be in a form \code{"qdb://<ip or hostname>:<port>[, ...]"}.
#' 
#' @param uri Cluster URI, e.g.: \code{"qdb://127.0.0.1:2836"}, \code{"qdb://10.0.1.1:2836,10.0.1.2:2837,my.database.com:2838"}.
#' @return Handle to the cluster
#' @export
#' @examples
#' handle <- qdb_connect("qdb://127.0.0.1:2836")
qdb_connect <- function(uri) {
    .Call('_quasardb__qdb_connect', PACKAGE = 'quasardb', uri)
}

#' Return error description.
#' 
#' Return error description string for a given error code.
#' 
#' @param code Error code.
#' @return Error description string.
#' @export
#' @examples
#' handle <- qdb_error(0)
qdb_error <- function(ierr) {
    .Call('_quasardb__qdb_error', PACKAGE = 'quasardb', ierr)
}

#' Return quasardb API version
#' 
#' Return version of the underlying quasardb C API.
#' 
#' @return API version
#' @export
#' @examples
#' qdb_version()
qdb_version <- function() {
    .Call('_quasardb__qdb_version', PACKAGE = 'quasardb')
}

