# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @backref src/attach_tags.cpp
#' @title Attach tags to an entry.
#'
#' @description
#' Attach one or many tags to an existing entry.
#'
#' When attaching tags, no error will be raised if the entry has been tagged
#' with at least one tag (i.e. when this entry had not already been tagged
#' with all given tags).
#'
#' @seealso \url{https://doc.quasardb.net/master/concepts/tags.html}
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param entry An alias (key) of an entry.
#' @param tags A vector of tag names to attach.
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' attach_tags(handle, "key", "tag")
attach_tags <- function(handle, entry, tags) {
  invisible(.Call("_quasardb__qdb_attach_tags"
                  , PACKAGE = "quasardb", handle, entry, tags))
}

#' @backref src/build.cpp
#' @title Return quasardb API build information.
#'
#' @description
#' Return build information of the underlying quasardb C API.
#'
#' Build information may be useful when a problem or a bug has
#' been encountered to precisely describe the version of the API used.
#'
#' @return API build information
#' @export
#'
#' @examples
#' build()
build <- function() {
  .Call("_quasardb__qdb_build", PACKAGE = "quasardb")
}

#' @backref src/connect.cpp
#' @title Connect to a quasardb cluster.
#'
#' @description
#' Connect to a quasardb cluster described with the given URI and returns a
#' handle to it.
#' The URI must be in a form \code{"qdb://<ip or hostname>:<port>[, ...]"}.
#'
#' @param uri Cluster URI, e.g.: \code{"qdb://127.0.0.1:2836"},
#'   \code{"qdb://10.0.1.1:2836,10.0.1.2:2837,my.database.com:2838"}.
#'
#' @return Handle to the cluster
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
connect <- function(uri = "qdb://127.0.0.1:2836") {
  .Call("_quasardb__qdb_connect", PACKAGE = "quasardb", uri)
}

#' @backref src/Detach_tags.cpp
#'
#' @title Detach tags from an entry.
#'
#' @description
#' Detach one or many tags from an existing entry.
#'
#' When detaching tags, no error will be raised if the entry has been untagged
#' from at least one tag (i.e. when this entry had no tags amongst the given
#' ones).
#'
#' @seealso \url{https://doc.quasardb.net/master/concepts/tags.html}
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param entry An alias (key) of an entry.
#' @param tags A vector of tag names to attach.
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' detach_tags(handle, entry = "key", tags = "tag")
#'
#' detach_tags(handle, entry = "key", tags = c("tag1", "tag2"))
detach_tags <- function(handle, entry, tags) {
  invisible(.Call("_quasardb__qdb_detach_tags"
                  , PACKAGE = "quasardb", handle, entry, tags))
}

#' @backref src/error.cpp
#' @title Return error description.
#'
#' @description
#' Return error description string for a given error code.
#'
#' @param code Error code.
#'
#' @return Error description string.
#' @export
#'
#' @examples
#' error(code = 0)
error <- function(code) {
  .Call("_quasardb__qdb_error", PACKAGE = "quasardb", code)
}

#' @backref src/find.cpp
#' @title Execute a find query.
#'
#' @description
#' Execute a query to find matching entries.
#' A find query should be composed of at least one `tag='some_tag'` part.
#' It may also limit the type of entries through the use of `type=?`.
#' The type may be one of: `blob`, `deque`, `int` (or `integer`), `stream`,
#' `tag` or `ts`.
#' Logical operations `and` and `or` as well as negation `not` may be used as
#' well.
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param query A query to execute.
#'
#' @return List of matching entry aliases/keys.
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' query_find(handle, "find(tag='my_tag' and type=ts)")
query_find <- function(handle, query) {
  .Call("_quasardb__qdb_query_find", PACKAGE = "quasardb", handle, query)
}

#' @backref src/get_tagged.cpp
#' @title Get tagged entries.
#'
#' @description
#' Return keys of all the entries tagged by the given tag.
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param tag An alias (key) of a tag.
#'
#' @return List of entries.
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' get_tagged(handle, tag = "tag")
get_tagged <- function(handle, tag) {
  .Call("_quasardb__qdb_get_tagged", PACKAGE = "quasardb", handle, tag)
}

#' @backref src/get_tags.cpp
#' @title Get tags.
#'
#' @description
#' Return all tags of an entry.
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param name An alias (key) of an entry.
#'
#' @return List of tags.
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' get_tags(handle, name = "key")
get_tags <- function(handle, name) {
  .Call("_quasardb__qdb_get_tags", PACKAGE = "quasardb", handle, name)
}

#' @backref src/query.cpp
#' @title Execute a query.
#'
#' @description
#' Execute a select query using SQL-like syntax.
#'
#' @seealso \url{https://doc.quasardb.net/master/api/queries.html.}
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param query A query to execute.
#'
#' @return A data frame with results of the query.
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' query(handle, "SELECT * FROM timeseries IN RANGE(2017, +1y)")
query <- function(handle, query) {
  .Call("_quasardb__qdb_query", PACKAGE = "quasardb", handle, query)
}

#' @backref src/remove.cpp
#' @title Remove an entry.
#'
#' @description
#' Remove an existing entry from the database.
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param name Timeseries name.
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' entry_remove(handle, "timeseries")
entry_remove <- function(handle, name) {
  invisible(.Call("_quasardb__qdb_remove", PACKAGE = "quasardb", handle, name))
}

#' @backref src/show.cpp
#' @title Describe a timeseries.
#'
#' @description
#' List columns, their names and types, of a timeseries.
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param name A name of the timeseries.
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' columns <- ts_show(handle, name = "ts")
ts_show <- function(handle, name) {
  .Call("_quasardb__qdb_show", PACKAGE = "quasardb", handle, name)
}

#' @backref src/ts_create.cpp
#' @title Create a timeseries.
#'
#' @description
#' Create a timeseries with given columns.
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param name A name of the to-be-created timeseries.
#' @param columns A named vector of `column_type` integers.
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' ts_create(handle,
#'   name = "ts",
#'   columns = c("col1" = column_type$blob, "col2" = column_type$double)
#' )
ts_create <- function(handle, name, columns) {
  invisible(.Call("_quasardb__qdb_ts_create"
                  , PACKAGE = "quasardb", handle, name, columns))
}

#' @backref src/ts_insert.cpp
#'
#' @title Insert floating-point data.
#'
#' @description
#' Insert floating-point data into double column of an existing timeseries.
#' This function is for test purposes only
#'
#' @seealso \code{\link{connect}}
#'
#' @param handle A valid cluster opened using `connect`.
#' @param name Timeseries name.
#' @param column Column name.
#'
#' @export
#'
#' @examples
#' handle <- connect("qdb://127.0.0.1:2836")
#' ts_double_insert(handle, "timeseries", "column")
ts_double_insert <- function(handle, name, column) {
  invisible(.Call("_quasardb__qdb_ts_double_insert"
                  , PACKAGE = "quasardb", handle, name, column))
}

#' @backref src/version.cpp
#' @title Return quasardb API version
#'
#' @description
#' Return version of the underlying quasardb C API.
#'
#' Version information may be useful when a problem or a bug has
#' been encountered to precisely describe the version of the API used.
#'
#' @return API version
#' @export
#'
#' @examples
#' version()
version <- function() {
  .Call("_quasardb__qdb_version", PACKAGE = "quasardb")
}
