# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @backref src/build.cpp
#' @title Return quasardb API build information.
#'
#' Return build information of the underlying quasardb C API.
#'
#' @return API build information
#' @export
#'
#' @examples
#' qdb_build()
qdb_build <- function() {
    .Call('_quasardb__qdb_build', PACKAGE = 'quasardb')
}

#' @backref src/connect.cpp
#' @title Connect to a quasardb cluster.
#'
#' Connect to a quasardb cluster described with the given URI and returns a
#'   handle to it. The URI must be in a form \code{"qdb://<ip or
#'   hostname>:<port>[, ...]"}.
#'
#' @param uri Cluster URI, e.g.: \code{"qdb://127.0.0.1:2836"},
#'   \code{"qdb://10.0.1.1:2836,10.0.1.2:2837,my.database.com:2838"}.
#'
#' @return Handle to the cluster
#'
#' @export
#'
#' @examples
#' handle <- qdb_connect("qdb://127.0.0.1:2836")
qdb_connect <- function(uri) {
    .Call('_quasardb__qdb_connect', PACKAGE = 'quasardb', uri)
}

#' @backref src/error.cpp
#' @title Return error description.
#'
#' Return error description string for a given error code.
#'
#' @param code Error code.
#'
#' @return Error description string.
#' @export
#'
#' @examples
#' handle <- qdb_error(0)
qdb_error <- function(ierr) {
    .Call('_quasardb__qdb_error', PACKAGE = 'quasardb', ierr)
}

#' @backref src/find.cpp
#' @title Execute a query to find matching entries.
#'
#' @param handle A valid cluster opened using qdb_connect.
#' @param query A query to execute.
#'
#' @return List of matching entry aliases/keys.
#' @export
#'
#' @examples
#' handle <- qdb_connect("qdb://127.0.0.1:2836")
#' qdb_find(handle, "find(tag='my_tag' and type=ts)")
qdb_find <- function(handle, query) {
    .Call('_quasardb__qdb_query_find', PACKAGE = 'quasardb', handle, query)
}

#' @backref src/query.cpp
#' @title Execute a query.
#'
#' @param handle A valid cluster opened using qdb_connect.
#' @param query A query to execute.
#'
#' @return A data frame with results of the query.
#' @export
#'
#' @examples
#' handle <- qdb_connect("qdb://127.0.0.1:2836")
#' qdb_query(handle, "SELECT * FROM timeseries IN RANGE(2017, +1y)")
qdb_query <- function(handle, query) {
    .Call('_quasardb__qdb_query', PACKAGE = 'quasardb', handle, query)
}

#' @backref src/ts_create.cpp
#' @title Create a timeseries.
#'
#' @param handle A valid cluster opened using qdb_connect.
#' @param name A name of the to-be-created timeseries.
#'
#' @export
#'
#' @examples
#' handle <- qdb_connect("qdb://127.0.0.1:2836")
#' qdb_ts_create(handle, name = "ts",
#'     columns = c("col1" = ColumnType$Blob, "col2" = ColumnType$Double))
qdb_ts_create <- function(handle, name, columns) {
    invisible(.Call('_quasardb__qdb_ts_create', PACKAGE = 'quasardb', handle, name, columns))
}

#' @backref src/version.cpp
#' @title Return quasardb API version
#'
#' Return version of the underlying quasardb C API.
#'
#' @return API version
#' @export
#'
#' @examples
#' qdb_version()
qdb_version <- function() {
    .Call('_quasardb__qdb_version', PACKAGE = 'quasardb')
}

